#!/usr/bin/env node
// build-index.mjs — regenerate the knowledge indexes from card frontmatter.
//
// The index is a BUILD ARTIFACT (DESIGN.md §2.3): never hand-maintained. This script
// is the single faithful writer of every `.knowledge/index.md`, run by the `materialize`
// workflow after cards change. No dependencies — Node stdlib only.
//
// Usage:  node build-index.mjs [rootDir]      (rootDir defaults to cwd)
//
// What it does:
//   - Finds every `.knowledge/` dir under rootDir that has a `cards/` subdir.
//   - For each PACKAGE store, writes <pkg>/.knowledge/index.md (that package's cards).
//   - For the ROOT store (<rootDir>/.knowledge), writes the AGGREGATOR index:
//       cross-cutting cards + every package's card summaries (the cross-package TOC,
//       DESIGN.md §3.3 — the breadth safety net).
//
// Card files that fail to parse are reported and skipped (never silently dropped).

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from "node:fs";
import { join, relative, sep, posix } from "node:path";

const rootDir = process.argv[2] ? process.argv[2] : ".";

// --- frontmatter parsing (minimal, dependency-free) ----------------------------
// Only the scalar fields the index routes on. Handles YAML folded continuations
// (an indented line with no `key:` continues the previous value).
const SCALARS = ["id", "title", "summary", "type", "topic", "status", "confidence"];

function parseFrontmatter(text) {
  const lines = text.split(/\r?\n/);
  if (lines[0]?.trim() !== "---") return null;
  const fm = {};
  let key = null;
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === "---") return fm; // end of frontmatter
    const m = line.match(/^([A-Za-z][\w-]*):\s?(.*)$/);
    if (m) {
      key = m[1];
      if (SCALARS.includes(key)) fm[key] = m[2].trim();
      else key = null; // list/other field — ignore its continuations
    } else if (key && /^\s+\S/.test(line) && fm[key] !== undefined) {
      fm[key] = (fm[key] + " " + line.trim()).trim(); // folded continuation
    }
  }
  return null; // never closed
}

// --- discovery -----------------------------------------------------------------
function findKnowledgeDirs(dir, found = []) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return found;
  }
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (e.name === "node_modules" || e.name === ".git") continue;
    const full = join(dir, e.name);
    if (e.name === ".knowledge") {
      if (existsSync(join(full, "cards"))) found.push(full);
      continue; // don't descend into a .knowledge dir
    }
    findKnowledgeDirs(full, found);
  }
  return found;
}

function readCards(cardsDir) {
  const cards = [];
  const problems = [];
  let files;
  try {
    files = readdirSync(cardsDir).filter((f) => f.endsWith(".md"));
  } catch {
    return { cards, problems };
  }
  for (const f of files) {
    const path = join(cardsDir, f);
    const fm = parseFrontmatter(readFileSync(path, "utf8"));
    if (!fm || !fm.id || !fm.summary) {
      problems.push(toPosix(relative(rootDir, path)) + " (missing frontmatter/id/summary)");
      continue;
    }
    cards.push(fm);
  }
  return { cards, problems };
}

// --- rendering -----------------------------------------------------------------
const GEN_NOTE = "<!-- GENERATED by tools/build-index.mjs — do not edit by hand -->";

function cardLine(c) {
  const meta = [c.type, c.topic].filter(Boolean).join(" · ");
  const stale = c.status && c.status !== "active" ? ` **[${c.status}]**` : "";
  return `- \`${c.id}\` — ${c.summary} _(${meta})_${stale}`;
}

function groupByTopic(cards) {
  const groups = new Map();
  for (const c of cards) {
    const t = c.topic || "(untopiced)";
    if (!groups.has(t)) groups.set(t, []);
    groups.get(t).push(c);
  }
  return [...groups.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([topic, list]) => [topic, list.sort((a, b) => a.id.localeCompare(b.id))]);
}

function renderTopicSections(cards) {
  if (cards.length === 0) return "_No cards yet._\n";
  return groupByTopic(cards)
    .map(([topic, list]) => `### ${topic}\n${list.map(cardLine).join("\n")}\n`)
    .join("\n");
}

function toPosix(p) {
  return p.split(sep).join(posix.sep);
}

// --- main ----------------------------------------------------------------------
const rootKnowledge = join(rootDir, ".knowledge");
const allDirs = findKnowledgeDirs(rootDir);
const allProblems = [];
const written = [];

// package stores = every .knowledge dir except the root one
const packageDirs = allDirs.filter((d) => relative(rootKnowledge, d) !== "");

// 1) per-package local indexes
const packageCards = []; // { label, cards }
for (const kdir of packageDirs) {
  const pkgPath = toPosix(relative(rootDir, join(kdir, ".."))) || ".";
  const { cards, problems } = readCards(join(kdir, "cards"));
  allProblems.push(...problems);
  packageCards.push({ label: pkgPath, cards });

  const body =
    `# \`${pkgPath}\` — knowledge index\n${GEN_NOTE}\n\n` +
    renderTopicSections(cards) +
    `\n_Glossary: see \`./CONTEXT.md\`._\n`;
  const out = join(kdir, "index.md");
  writeFileSync(out, body);
  written.push(toPosix(relative(rootDir, out)));
}

// 2) root aggregator index (cross-cutting cards + every package's cards)
if (existsSync(rootKnowledge)) {
  const { cards: crossCutting, problems } = readCards(join(rootKnowledge, "cards"));
  allProblems.push(...problems);

  let body = `# Root knowledge index — cross-package TOC\n${GEN_NOTE}\n\n`;
  body +=
    "> Always read this at task start. It lists every card in the monorepo (one line each),\n" +
    "> including packages you never open. Open a package's local index for full local depth.\n\n";

  body += `## Cross-cutting\n${renderTopicSections(crossCutting)}\n`;

  for (const { label, cards } of packageCards.sort((a, b) => a.label.localeCompare(b.label))) {
    body += `## ${label}\n${renderTopicSections(cards)}\n`;
  }
  body += "_Glossaries: see `./CONTEXT-MAP.md`._\n";

  const out = join(rootKnowledge, "index.md");
  writeFileSync(out, body);
  written.push(toPosix(relative(rootDir, out)));
}

// --- report --------------------------------------------------------------------
console.log(`build-index: wrote ${written.length} index file(s) under ${toPosix(rootDir)}`);
for (const w of written) console.log(`  + ${w}`);
if (allProblems.length) {
  console.log(`build-index: ${allProblems.length} card(s) skipped:`);
  for (const p of allProblems) console.log(`  ! ${p}`);
  process.exitCode = 1;
}
